name: NodeJS with Webpack

on:
  pull_request:
    branches: [main]
  push:
    branches: [Guilherme]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obter codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        working-directory: ./front
        run: npm ci

      - name: Compilar frontend
        working-directory: ./front
        run: npm run build